# Generated by Django 5.0.1 on 2024-02-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0002_alter_outbound_date_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
