# Generated by Django 5.0.1 on 2024-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('date_received', models.IntegerField()),
                ('product_sku', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
